# Generated by Django 4.0.3 on 2022-05-10 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_imagebanner_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
