# Generated by Django 4.0.3 on 2022-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_remove_orderitem_variation_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebanner',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='categorie de produit'),
        ),
        migrations.AddField(
            model_name='imagebanner',
            name='price',
            field=models.FloatField(null=True, verbose_name='Prix promotion'),
        ),
        migrations.AddField(
            model_name='imagebanner',
            name='titel',
            field=models.CharField(max_length=50, null=True, verbose_name='Titre de banner'),
        ),
    ]
