# Generated by Django 4.0.3 on 2022-06-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_toastmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toastmessage',
            name='image',
        ),
    ]
