# Generated by Django 4.0.3 on 2022-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='uuid_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
