# Generated by Django 4.0.3 on 2022-06-22 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_orderitem_uuid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
