# Generated by Django 4.0.3 on 2022-06-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_alter_orderitem_uuid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='uuid_id',
        ),
    ]
