# Generated by Django 4.0.3 on 2022-06-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_remove_orderitem_uuid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='freeshipping',
            field=models.BooleanField(default=False),
        ),
    ]
