# Generated by Django 4.0.3 on 2022-06-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_shippingaddress_is_stopdesk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='freeshipping',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_stopdesk',
        ),
    ]
