# Generated by Django 4.0.3 on 2022-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_shippingaddress_name_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_home',
            field=models.BooleanField(default=False),
        ),
    ]
