# Generated by Django 4.0.3 on 2022-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_remove_shippingaddress_shipping_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='is_stopdesk',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
