# Generated by Django 4.0.3 on 2022-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_sould',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
