# Generated by Django 4.0.3 on 2022-06-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_product_count_sould_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='etage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
